elsa-hanke/elsa-backend

src/main/kotlin/fi/elsapalvelu/elsa/domain/Asiakirja.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/AsiakirjaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TyoskentelyjaksoDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TyoskentelyjaksoFormDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/AsiakirjaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/validation/FileValidator.kt
src/main/kotlin/fi/elsapalvelu/elsa/validation/impl/FileValidatorImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariAsiakirjaResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariAsiakirjaResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/AsiakirjaHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/KayttajaHelper.kt

- Receive tyoskentelyjakso data (create and update) as json string within multipart/form-data because of the file attachments included
- Use AsiakirjaService to save new files and delete the deleted ones. Do not use bidirectional relation between asiakirja and tyoskentelyjakso because asiakirjat data is fetched using projection (to avoid loading file data unnecessarily).
- If tyoskentelyjakso is deleted, do not delete assosiated asiakirjat but just remove the reference

UOELSA-496: Asiakirjan liittäminen työskentelyjaksoon

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Asiakirja.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/AsiakirjaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/AsiakirjaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariAsiakirjaResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariAsiakirjaResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/AsiakirjaHelper.kt
src/test/resources/config/application.yml

- Create BlobProxy object with file input stream and size to prevent storing any file content bytes in heap memory

UOELSA-513: Convert data in Asiakirja entity as Blob

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKoulutussopimusServiceImpl.kt

- Muutoin toisen kouluttajan allekirjoituksen yhteydessä virhe java.util.ConcurrentModificationException

UOELSA-636: Muunna kouluttajat arrayksi ennen muokkausta ja tallennusta

---

docs/depcheck-report-20210823.md
owasp-suppressions.xml

Lisätty muutama suppress-sääntö OWASP Dependency Checkille ja kirjattu ylös havaintoja sen löydöksistä.

UOELSA-377: vaiennetaan dependency checkin false positivet

---

src/main/resources/config/liquibase/changelog/20211209114123_modify_audit_constraints_KoejaksonKoulutussopimus.xml
src/main/resources/config/liquibase/changelog/20211209114446_modify_audit_constraints_KoejaksonAloituskeskustelu.xml
src/main/resources/config/liquibase/master.xml

- Poista not null constraintit koulutussopimuksen ja aloituskeskustelun audit-tauluista niiden kenttien osalta, jotka pitää pystyä tallentamaan tyhjänä (= tallenna keskeneräisenä)

UOELSA-546: Korjaa audit-taulujen not null constraintit

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/ArvioitavanKokonaisuudenKategoria.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ArvioitavanKokonaisuudenKategoriaDTO.kt
src/main/resources/config/liquibase/changelog/20220113123834_add_erikoisala_data_syopataudit.xml
src/main/resources/config/liquibase/changelog/20220114084411_delete_old_testdata.xml

- Poista foreign key virheellisen datan poiston ajaksi
- Uudelleennimeä arvioitavan kokonaisuuden ja arvioitavan kokonaisuuden kategorian constraintit
- Poista NotNull attribuutit arvioitavan kokonaisuuden kategorian jarjestysnumerolta

UOELSA-911: Korjaa kantamigraatio

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintosuorituksetPersistenceServiceImpl.kt
src/main/resources/config/liquibase/changelog/20220408121744_modify_entity_OpintosuoritusOsakokonaisuus.xml
src/main/resources/config/liquibase/master.xml

- Päivitä vanhenemispäivämäärä vaikka se olisi lähdedatassa null
- Poista tarpeeton sarake opintosuoritus_osakokonaisuus taulusta

UOELSA-1065: Korjaa opintosuoritusten päivittäminen

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/ErikoistuvaLaakariRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/OpintooikeusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoistuvaLaakariService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintooikeusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/constants/Constants.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ErikoistuvaLaakariServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintooikeusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKaytonAloitusResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariMuutToiminnotResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/ErikoisalaHelper.kt

- Siirrä opinto-oikeuksien filtteröinti JPA-queryyn ja hae vain voimassaolevat ja kirjautumisen sallivan tilan omaavat opinto-oikeudet
- Mikäli käyttäjän valitsema opinto-oikeus ei ole enää voimassa myöhemmällä kirjautumiskerralla, aseta aktiiviseksi opinto-oikeudeksi ensimmäinen voimassaoleva, jonka tila sallii kirjautumisen

UOELSA-1144: Tarkista opinto-oikeuden voimassaolo kirjautumisen yhteydessä

---

src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonAloituskeskusteluDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonKehittamistoimenpiteetDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonLoppukeskusteluDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonValiarviointiDTO.kt

- Aseta opiskelijatunnus ei pakolliseksi AloituskeskusteluDTO:ssa, ValiarviointiDTO:ssa, KehittamistoimenpiteetDTO:ssa ja LoppukeskusteluDTO:ssa, koska kyseistä tietoa ei käytetä tallennuksen yhteydessä vaan opiskelijatunnus haetaan opintooikeus-taulusta.

UOELSA-1175: Aseta opiskelijatunnus ei pakolliseksi

---

src/main/resources/config/liquibase/changelog/20220923114933_modify_erikoisala_nimet.xml
src/main/resources/config/liquibase/master.xml

- Muokkaa nimeä niille hammaslääketieteen erikoisaloille, jotka ovat samannimisiä kuin lääketieteellä

UOELSA-1187: Muokkaa erikoisalanimet

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt
src/test/kotlin/fi/elsapalvelu/elsa/service/TyoskentelyjaksonPituusCounterServiceTest.kt

Työskentelyjaksojen hyväksiluettujen päivien logiikka hajoaa, jos työskentelyjaksolla ei ole päättymispäivämäärää ja keskeytys sijoittuu seuraavalle vuodelle

ELSA-255: Korjaus työskentelyjaksojen hyväksiluettujen päivien laskuun

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/ErikoistuvaLaakari.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/OpintooikeusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoistuvaLaakariService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintooikeusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ErikoistuvaLaakariServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintooikeusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintotietodataPersistenceServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajaResource.kt
src/main/resources/config/liquibase/changelog/20240422151300_modify_entity_ErikoistuvaLaakari.xml
src/main/resources/config/liquibase/master.xml

- Erikoistujalla voi olla vain yksi opinto-oikeus käytössä kerrallaan
- Erikoistujan ja YEK-roolin vaihdossa katoaa tieto mikä opinto-oikeus oli käytössä ennen vaihtoa, joten lisätään sille oma kenttä

YEK-1566: Päivitä käytössä oleva opinto-oikeus roolin vaihdossa

---

.github/workflows/actions.yml

Github Actions hyötyjä:
- Ei rajoituksia montako samanaikaista runneria
- Ajot näkee suoraan githubista
- Ympäristökohtaisia asetuksia ja muuttujia voidaan hallitan githubista
Muita parannuksia:
- Github OIDC käyttöön jolloin ei tarvita erillisiä AWS käyttäjiä CI:lle vaan githubia varten tehdään aina väliaikainen pääsy
- Ei ajeta testejä useaan kertaan
- jib tekee docker imagen suoraan ecr:ään
Huomioita:
- Toistaiseksi jätetty azure devops konfiguraatio myös paikalleen, voidaan ottaa pois jossain kohti jos actions toimii vakaasti
- Releasen yhteydessä täytyy seurata meneekö deploy läpi
- Cache luodaan vain main branchista, muissa read only tilassa. Seurattava käytetäänkö cachea oikein.

Github actions käyttöön

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintotietodataPersistenceServiceImpl.kt

YEK-1597: Uusi YEK oikeus ei saa vaihtaa erikoistumisen aktiivista opinto-oikeutta

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintotietodataPersistenceServiceImpl.kt

Jos käyttäjälle löytyy pelkkä YEK opinto-oikeus, muodostetaan sille ensimmäisellä kerralla rooli oikein. Seuraavalla kirjautumisella hänelle muodostuu kuitenkin lisäksi EL rooli. Jos käyttäjä yrittää vaihtaa roolia EL:ksi, heitetään hänet ulos järjestelmästä eikä hän pääse takaisin sisälle. Poistetaan ylimääräinen roolin muodostus.

YEK-1599: Ei luoda ylimääräistä EL roolia

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajienYhdistaminenServiceImpl.kt

JPA ei aja SQL komentoja heti, vaan vasta transaktion lopussa. Komennot ajetaan seuraavassa järjestyksessä:
1. Inserts, in the order they were performed
2. Updates
3. Deletion of collection elements
4. Insertion of collection elements
5. Deletes, in the order they were performed 
Toisen käyttäjän sähköposti yritetään päivittää ennen kuin toinen käyttäjä poistetaan. Pakotetaan SQL ajo käyttäjän poiston yhteydessä, jotta toisen käyttäjän päivityksen yhteydessä ei tule konflikteja.

ELSA-486: Pakota käyttäjän poisto ennen toisen käyttäjän päivitystä

---

build.gradle
gradle.properties

- Spring boot 3.3.6
- Ei yliajeta spring-cloud-starterin tarjoamaa aws-corea

Korjaus s3 resurssien hakuun

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVastuuhenkilonArvioServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TerveyskeskuskoulutusjaksonHyvaksyntaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KoejaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResource.kt
src/main/resources/config/liquibase/data/erikoisala/anestesia/2022-06-06/arvioitava_kokonaisuus.csv
src/main/resources/i18n/messages.properties
src/main/resources/templates/mail/arviointiaMuokattuEmail.html
src/main/resources/templates/mail/katseluoikeudet.html
src/main/resources/templates/mail/uusiErikoistuvaLaakari.html
src/main/resources/templates/mail/uusiKouluttaja.html
src/main/resources/templates/mail/uusiKouluttajaRooli.html
src/main/resources/templates/mail/uusiVastuuhenkilo.html
src/main/resources/templates/mail/uusivalmistumispyynto.html
src/main/resources/templates/mail/valmistumispyyntoTarkastettavissaVastuuhenkilo.html
src/main/resources/templates/mail/vastuuhenkilonArvioKuitattava.html

- Poistettu käytöstä heräte virkailijalle, kun vastuuhenk. on hyväksynyt koejakson.
- Tk-koul.jakson hyväksyntä vaihdettu virkailijan email -> opintohallinnon email.
- Uusi heräte ja sähköposti vastuuhenkilölle, valmistumispyyntoTarkastettavissaVastuuhenkilo
Aikaisemmin sama kuin virkailijalle, nyt vstuuhenkilölle uudet tekstit.
- Tekstimuutoksia.

muutoksia heratteet ja tekstit

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajaQueryService.kt

Vaihdettu email!! --> email.toString(), joka tarkoittaa, että vaikka email = null, mäppäys ei hajoa, mutta emailina palautuu null tekstinä. Korjaa ongelman, joka aiheutti, että tyhjä sähköposti hajottaa käyttäjien yhdistyksen.
Tarkistettu mapKayttajaErikoistujaKouluttaja() käyttö: sitä käytetään pelkästään käyttäjätilien yhdistämisen hakuun eli ei pitäisi tulla outouksia muualle. Virkailijat/tekniset pääkäyttäjät näkee null arvon käyttäjätilien yhdistyksessä.

ELSA-890: Vaihdettu email!! --> email.toString()

---

src/main/kotlin/fi/elsapalvelu/elsa/service/dto/arkistointi/PublicityClass.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/arkistointi/RecordProperties.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/arkistointi/Restriction.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ArkistointiServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVastuuhenkilonArvioServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt

- Myös YEK valmistumiset tulee arkistoida
- Salassapitoperuste on tarvittaessa julkisuuslain pykäläkohta

Korjaus YEK valmistumisien arkistointiin ja arkistoinnin metatietoihin
