elsa-hanke/elsa-backend

src/main/kotlin/fi/elsapalvelu/elsa/domain/Asiakirja.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/AsiakirjaData.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/Tyoskentelyjakso.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/AsiakirjaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/AsiakirjaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/TyoskentelyjaksoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/AsiakirjaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/AsiakirjaDataDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TyoskentelyjaksoDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/AsiakirjaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/AsiakirjaDataMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/AsiakirjaMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/projection/AsiakirjaItemProjection.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/projection/AsiakirjaListProjection.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariAsiakirjaResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/main/resources/config/liquibase/changelog/20210528103633_added_entity_AsiakirjaData.xml
src/main/resources/config/liquibase/changelog/20210528103748_modify_entity_Asiakirja.xml
src/main/resources/config/liquibase/changelog/20210528103748_modify_entity_constaints_Asiakirja.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariAsiakirjaResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/AsiakirjaHelper.kt

- Set fetchType = lazy to get asiakirjat for listings without the actual data
- Set bidirectional relation between Tyoskentelyjakso and Asiakirja

UOELSA-513: [Refactor] Extract Asiakirja data into separate table

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/KayttajaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KayttajaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ArviointipyyntoFormDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KayttajaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoritusarvioinnitOptionsDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/KayttajaMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritusarviointiResource.kt

- Palauta kouluttajien lisäksi vastuuhenkilöt, jotta erikoistuvalla mahdollisuus lähettää arviointipyyntö myös vastuuhenkilölle
- Lisää authorities-lista KayttajaDTO:hon, koska frontendin puolella tarvitsee tietää mitkä henkilöt listassa ovat vastuuhenkilöitä

UOELSA-558: Arviointipyynnön lähettäminen vastuuhenkilölle

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/KoejaksonValiarviointi.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/enumeration/KehittamistoimenpideKategoria.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonValiarviointiDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/KoejaksoTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKehittamistoimenpiteetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKoulutussopimusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVaiheetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonValiarviointiServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResource.kt
src/main/resources/config/liquibase/changelog/20210819100902_modify_entity_KoejaksonValiarviointi.xml
src/main/resources/config/liquibase/master.xml

- lisätty väliarvioinnin kategoriat enumeina
- korjattu validointeja niin ettei uusi arviointivaihe saa sisältää erikoistuvan allekirjoitusta
- korjattu tiloja erikoistuvalle

UOELSA-269: Lisätty väliarvioinnin kategoriat ja korjattu validointeja ja tiloja

---

src/main/kotlin/fi/elsapalvelu/elsa/service/TyoskentelyjaksoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt

- Heitä endpointilta BadRequestAlertException mikäli poistaminen epäonnistuu

UOELSA-744: Palauta serviceltä false mikäli työskentelyjakson poistaminen epäonnistuu

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt

- Pyöristä työskentelyjakson/jaksojen yhteenlaskettu pituus lähimpään kokonaislukuun

UOELSA-717: Pyöristä lähimpään kokonaislukuun

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/KoulutussuunnitelmaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/AsiakirjaServiceImpl.kt

- Tarkista asiakirjaa poistettaessa, onko koulutussuunnitelmasta viittaus siihen. Jos viittaus löytyy, poista se.

UOELSA-850: Koulutussuunnitelmaan liitetyn asiakirjan poisto

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Seurantajakso.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/SeurantajaksoRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SeurantajaksoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SeurantajaksoDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/SeurantajaksoTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SeurantajaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/SeurantajaksoMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSeurantakeskustelutResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaSeurantakeskustelutResource.kt
src/main/resources/i18n/messages.properties
src/main/resources/templates/mail/seurantajaksoArvioitu.html
src/main/resources/templates/mail/seurantajaksoHyvaksytty.html
src/main/resources/templates/mail/seurantajaksoPalautettu.html
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaSeurantakeskustelutResourceIT.kt

- seurantakeskusteluiden arviointi/hyväksyntä kouluttajalle
- herätteet tapahtumista

UOELSA-586: Seurantakeskusteluiden listaus, arviointi ja hyväksyminen kouluttajalle

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Suoritusarviointi.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SuoritusarviointiQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/criteria/SuoritusarviointiCriteria.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoritusarviointiDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SeurantajaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SuoritusarviointiServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/SuoritusarviointiMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/SuoritusarviointiResource.kt
src/main/resources/config/liquibase/changelog/20211118171022_modify_entity_Suoritusarviointi.xml
src/main/resources/config/liquibase/changelog/20211118171022_modify_entity_constraints_Suoritusarviointi.xml
src/main/resources/config/liquibase/changelog/20211119173244_modify_entity_constraints_Suoritusarviointi.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritusarviointiResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/SuoritusarviointiHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaSuoritusarviointiResourceIT.kt

UOELSA-643: Käytettävyystestikorjaukset arvioinnit

---

src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/KoulutussuunnitelmaMapper.kt

- Älä mäppää pelkän id:n perusteella, jolloin muut tiedot jäävät tyhjiksi

UOELSA-888: Korjaa koulutussuunnitelman asiakirjojen mäppäys

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Oppimistavoite.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/OppimistavoitteenKategoria.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/Suoritemerkinta.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/OppimistavoiteDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/OppimistavoitteenKategoriaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/OppimistavoitteetTableDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoritemerkintaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoritemerkintaFormDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritemerkintaResource.kt
src/main/resources/config/liquibase/changelog/20211125160641_modify_entity_Oppimistavoite.xml
src/main/resources/config/liquibase/changelog/20211129175050_modify_entity_constraints_Suoritemerkinta.xml
src/main/resources/config/liquibase/changelog/20211130112633_modify_entity_OppimistavoitteenKategoria.xml
src/main/resources/config/liquibase/master.xml

UOELSA-642: kälitestikorjaukset

---

src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TyoskentelyjaksotTableDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/main/resources/config/liquibase/changelog/20211214131634_modify_entity_data_PoissaolonSyy.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt

Uoelsa 641 käytettävyystestikorjaukset työskentelyjaksot

---

src/main/resources/config/liquibase/changelog/20220111170325_add_erikoisala_data_lastenneurologia.xml
src/main/resources/config/liquibase/data/erikoisala/lastenneurologia/arvioitava_kokonaisuus.csv
src/main/resources/config/liquibase/data/erikoisala/lastenneurologia/arvioitavan_kokonaisuuden_kategoria.csv
src/main/resources/config/liquibase/data/erikoisala/lastenneurologia/suorite.csv
src/main/resources/config/liquibase/data/erikoisala/lastenneurologia/suoritteen_kategoria.csv
src/main/resources/config/liquibase/master.xml

UOELSA-944: arvioitavat kokonaisuudet ja suoritteet lastenneurologia

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Erikoisala.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/Opintoopas.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ErikoisalaServiceImpl.kt
src/main/resources/config/liquibase/changelog/20220112155954_add_erikoisala_data_tyoterveyshuolto.xml
src/main/resources/config/liquibase/changelog/20220112161321_modify_entity_Opintoopas.xml
src/main/resources/config/liquibase/data/erikoisala/tyoterveyshuolto/arvioitava_kokonaisuus.csv
src/main/resources/config/liquibase/data/erikoisala/tyoterveyshuolto/arvioitavan_kokonaisuuden_kategoria.csv
src/main/resources/config/liquibase/data/erikoisala/tyoterveyshuolto/suorite.csv
src/main/resources/config/liquibase/data/erikoisala/tyoterveyshuolto/suoritteen_kategoria.csv
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/ErikoistuvaLaakariHelper.kt

UOELSA-926: Lisää erikoisalan työterveyshuolto tuotantodata

---

src/main/resources/i18n/messages.properties
src/main/resources/templates/mail/aloituskeskusteluHyvaksyttyKouluttaja.html
src/main/resources/templates/mail/aloituskeskusteluKouluttajalle.html
src/main/resources/templates/mail/aloituskeskusteluPalautettuKouluttaja.html
src/main/resources/templates/mail/arviointiAnnettuEmail.html
src/main/resources/templates/mail/arviointiaMuokattuEmail.html
src/main/resources/templates/mail/arviointipyyntoKouluttajalleEmail.html
src/main/resources/templates/mail/kehittamistoimenpiteetHyvaksytty.html
src/main/resources/templates/mail/kehittamistoimenpiteetKouluttajalle.html
src/main/resources/templates/mail/kehittamistoimenpiteetKuitattava.html
src/main/resources/templates/mail/koulutussopimusHyvaksyttyKouluttaja.html
src/main/resources/templates/mail/koulutussopimusPalautettuKouluttaja.html
src/main/resources/templates/mail/koulutussopimusVastuuhenkilolle.html
src/main/resources/templates/mail/loppukeskusteluHyvaksytty.html
src/main/resources/templates/mail/loppukeskusteluKouluttajalle.html
src/main/resources/templates/mail/loppukeskusteluKuitattava.html
src/main/resources/templates/mail/suoritusarvioinninKommenttiEmail.html
src/main/resources/templates/mail/uusiErikoistuvaLaakari.html
src/main/resources/templates/mail/valiarviointiHyvaksytty.html
src/main/resources/templates/mail/valiarviointiKouluttajalle.html
src/main/resources/templates/mail/valiarviointiKuitattava.html
src/main/resources/templates/mail/vastuuhenkilonArvioHyvaksytty.html
src/main/resources/templates/mail/vastuuhenkilonArvioKuitattava.html

UOELSA-949: Termimuutoksia ja korjauksia

---

src/main/resources/config/liquibase/changelog/20220114084411_delete_old_testdata.xml
src/main/resources/config/liquibase/master.xml

- Arvioitava kokonaisuus
- Arvioitavan kokonaisuuden kategoria
- Suorite
- Suoritteen kategoria

UOELSA-900: Poista vanha testidata

---

src/main/resources/config/liquibase/changelog/20220110154814_add_erikoisala_data_lastentaudit.xml
src/main/resources/config/liquibase/data/erikoisala/lastentaudit/arvioitava_kokonaisuus.csv
src/main/resources/config/liquibase/data/erikoisala/lastentaudit/arvioitavan_kokonaisuuden_kategoria.csv
src/main/resources/config/liquibase/data/erikoisala/lastentaudit/suorite.csv
src/main/resources/config/liquibase/data/erikoisala/lastentaudit/suoritteen_kategoria.csv
src/main/resources/config/liquibase/master.xml

Tehty UOELSA-900 vasten. Ei voida mergetä ennen.

UOELSA-907: Lastentaudit

---

src/main/resources/config/liquibase/changelog/20220119154329_add_erikoisala_data_ihotaudit.xml
src/main/resources/config/liquibase/data/erikoisala/ihotaudit/arvioitava_kokonaisuus.csv
src/main/resources/config/liquibase/data/erikoisala/ihotaudit/arvioitavan_kokonaisuuden_kategoria.csv
src/main/resources/config/liquibase/data/erikoisala/ihotaudit/suorite.csv
src/main/resources/config/liquibase/data/erikoisala/ihotaudit/suoritteen_kategoria.csv
src/main/resources/config/liquibase/master.xml

UOELSA-912: Ihotaudit erikoisalan data

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/config/WebConfigurer.kt

UOELSA-882: Lisää HSTS header

---

src/main/resources/config/liquibase/changelog/20220119102510_add_erikoisala_data_yleislaaketiede.xml
src/main/resources/config/liquibase/data/erikoisala/yleislaaketiede/arvioitava_kokonaisuus.csv
src/main/resources/config/liquibase/data/erikoisala/yleislaaketiede/arvioitavan_kokonaisuuden_kategoria.csv
src/main/resources/config/liquibase/master.xml

UOELSA-945: Vie erikoisalan yleislääketiede tuotantodata

---

src/main/resources/config/liquibase/changelog/20220201163548_add_erikoisala_data_anestesia.xml
src/main/resources/config/liquibase/data/erikoisala/anestesia/arvioitava_kokonaisuus.csv
src/main/resources/config/liquibase/data/erikoisala/anestesia/arvioitavan_kokonaisuuden_kategoria.csv
src/main/resources/config/liquibase/data/erikoisala/anestesia/suorite.csv
src/main/resources/config/liquibase/data/erikoisala/anestesia/suoritteen_kategoria.csv
src/main/resources/config/liquibase/master.xml

UOELSA-928: Anestesia erikoisalan data

---

src/main/resources/config/liquibase/changelog/20220127145440_modify_sequence_generators.xml
src/main/resources/config/liquibase/changelog/20220202122818_update_arviointityokalut_data.xml
src/main/resources/config/liquibase/changelog/20220202125003_update_opintoopas_data.xml
src/main/resources/config/liquibase/master.xml

UOELSA-971: Arviointiyokalujen paivitys

---

src/main/resources/config/application.yml

UOELSA-1007: Kasvata session timeout tuntiin

---

src/main/resources/config/liquibase/changelog/20220202134411_drop_table_yliopisto_erikoisala.xml
src/main/resources/config/liquibase/master.xml

UOELSA-1009: Poista yliopisto_erikoisala -taulu

---

src/main/resources/config/liquibase/changelog/20220204122234_added_entity_YliopistoErikoisala.xml
src/main/resources/config/liquibase/master.xml

UOELSA-1015: Lisää takaisin yliopisto_erikoisala -taulu

---

src/main/kotlin/fi/elsapalvelu/elsa/config/CacheConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/Erikoisala.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/Opintoopas.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/OpintoopasRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintoopasService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/OpintoopasDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintoopasServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/OpintoopasMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTeoriakoulutusResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaKayttajahallintaResource.kt
src/main/resources/config/liquibase/changelog/20220204145123_modify_entity_Opintoopas.xml
src/main/resources/config/liquibase/master.xml

- Hae kaikki opinto-oppaat uutta erikoistujaa lisättäessä eikä vain niitä mitkä ovat voimassa nykyhetkenä

UOELSA-923: Hae kaikki opinto-oppaat

---

src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariAsiakirjaResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoulutusjaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariMuutToiminnotResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariPaivakirjamerkintaResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSeurantakeskustelutResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritemerkintaResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritusarviointiResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTeoriakoulutusResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/ErikoistuvaLaakariHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/OpintooikeusHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/OpintoopasHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/TyoskentelyjaksoHelper.kt

UOELSA-995: Lisää integraatiotestit

---

azure-pipelines.yml

Uoelsa 1022 azure pipelines konffimuutokset

---

owasp-suppressions.xml

UOELSA-1042: Lisää h2 CVE:t false positiveihin

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/ErikoistuvaLaakariRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/OpintooikeusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoistuvaLaakariService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/EtusivuService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/TyoskentelyjaksoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ErikoistujanEteneminenDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ErikoistujienSeurantaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KayttajaErikoisalatPerYliopistoDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ErikoistuvaLaakariServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloEtusivuResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/ErikoistuvaLaakariHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/SeurantajaksoHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/SuoritusarviointiHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/TyoskentelyjaksoHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloEtusivuResourceIT.kt

UOELSA-867: Erikoistujien seuranta vastuuhenkilön etusivulle

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/OpintooikeusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/EtusivuService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaEtusivuResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaEtusivuResourceIT.kt

UOELSA-869: Erikoistujien seuranta kouluttajan etusivulle

---

src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoritteetTableDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritemerkintaResource.kt

UOELSA-962: Suoritteiden kategorioiden järjestäminen hajoaa, jos järjestysnumerot puuttuvat

---

src/main/resources/config/liquibase/changelog/20220110154814_add_erikoisala_data_lastentaudit.xml

Korjaus lastentautien dataan

---

azure-pipelines-sandbox.yml
azure-pipelines.yml

Uoelsa 986 huoltokatkosivu pipeline

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/OpintooikeusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintooikeusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/UserService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KaytonAloitusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/OpintooikeusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintooikeusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/UserServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKaytonAloitusResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajaResourceWithMockUserIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKaytonAloitusResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/OpintooikeusHelper.kt

Feature/uoelsa 975 kirjautuminen sähköpostiosoite

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/Erikoisala.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/ErikoisalaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoisalaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/OpintooikeusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ErikoisalaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintooikeusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/OpintooikeusMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaKayttajahallintaResource.kt
src/main/resources/config/liquibase/changelog/20220323124645_modify_entity_Erikoisala.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaKayttajahallintaResourceIT.kt

Feature/uoelsa 1060 tuotantokäytön laajentaminen erikoisalakohtaisesti

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/KoejaksonValiarviointi.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonValiarviointiDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/KoejaksoTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonValiarviointiServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/KoejaksonValiarviointiMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaKoejaksoResource.kt
src/main/resources/config/liquibase/changelog/20220405143538_modify_entity_KoejaksonValiarviointi.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/KoejaksonVaiheetHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaKoejaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloKoejaksoResourceIT.kt

UOELSA-1096: Koejakson väliarvioinnin osallisten sen hetkisiä tietojaei tarvitse tallentaa kantaan ja erikoistuja ei allekirjoita arviointia

---

src/main/kotlin/fi/elsapalvelu/elsa/config/ApplicationProperties.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/KoejaksonKoulutussopimus.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KoejaksonKoulutussopimusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SarakesignService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonKoulutussopimusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/sarakesign/SarakeSignDocumentMetadataDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/sarakesign/SarakeSignPhaseDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/sarakesign/SarakeSignRecipientDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/sarakesign/SarakeSignRecipientFieldsDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/sarakesign/SarakeSignRequestDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/sarakesign/SarakeSignResponseDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/sarakesign/SarakeSignResponseRequestDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonAloituskeskusteluServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKoulutussopimusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVaiheetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SarakesignServiceImpl.kt
src/main/resources/config/application.yml
src/main/resources/config/liquibase/changelog/20220414150148_modify_entity_KoejaksonKoulutussopimus.xml
src/main/resources/config/liquibase/master.xml

UOELSA-1054: Lähetetään koulutussopimus sarakesigniin allekirjoitettavaksi

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/KoejaksonKehittamistoimenpiteet.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonKehittamistoimenpiteetDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/KoejaksoTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKehittamistoimenpiteetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/KoejaksonKehittamistoimenpiteetMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaKoejaksoResource.kt
src/main/resources/config/liquibase/changelog/20220405163027_modify_entity_KoejaksonKehittamistoimenpiteet.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/KoejaksonVaiheetHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaKoejaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloKoejaksoResourceIT.kt

UOELSA-1097: Koejakson kehittämistoimenpiteiden osallisten sen hetkisiä tietoja ei tarvitse tallentaa kantaan ja erikoistuja ei allekirjoita vaihetta

---

src/main/kotlin/fi/elsapalvelu/elsa/service/KouluttajavaltuutusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonAloituskeskusteluServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKehittamistoimenpiteetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKoulutussopimusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonLoppukeskusteluServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonValiarviointiServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KouluttajavaltuutusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SeurantajaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKouluttajavaltuutusResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritusarviointiResource.kt
src/main/resources/config/liquibase/changelog/20220505094631_modify_entity_constraints_KouluttajaValtuutus.xml
src/main/resources/config/liquibase/master.xml

UOELSA-936: Lisätään kouluttajalle valtuutus arviointipyynnön, koejakson vaiheiden ja seurantajakson yhteydessä

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/KoejaksonVastuuhenkilonArvio.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonVastuuhenkilonArvioRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KoejaksonVaiheetService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KoejaksonVastuuhenkilonArvioQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KoejaksonVastuuhenkilonArvioService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/criteria/KoejaksoCriteria.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonVastuuhenkilonArvioDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/VastuuhenkilonArvioFormDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/KoejaksoTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVaiheetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVastuuhenkilonArvioServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/KoejaksonVastuuhenkilonArvioMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloKoejaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaKoejaksoResource.kt
src/main/resources/config/liquibase/changelog/20220509123801_modify_entity_KoejaksonVastuuhenkilonArvio.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloEtusivuResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloKoejaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaKoejaksoResourceIT.kt

UOELSA-845: Koejakson E-arviointilomakkeen muutokset

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajahallintaValidationServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajahallintaResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariMuutToiminnotResource.kt
src/main/resources/config/liquibase/changelog/20220621161234_insert_paakayttaja_role_for_tests.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/common/KayttajahallintaResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariMuutToiminnotResourceIT.kt

UOELSA-785: Toteuta pääkäyttäjien hallinta

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonAloituskeskusteluRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonKehittamistoimenpiteetRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonKoulutussopimusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonLoppukeskusteluRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonValiarviointiRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonVastuuhenkilonArvioRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KoejaksonVaiheetService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVaiheetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaEtusivuResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloEtusivuResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaEtusivuResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/KoejaksonVaiheetHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaEtusivuResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloEtusivuResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaEtusivuResourceIT.kt

UOELSA-870: Koejaksot etusivulle

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Kayttaja.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/SuoritusarviointiRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SuoritusarviointiService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/EtusivuArviointipyyntoDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SuoritusarviointiServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/SuoritusarviointiResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaSuoritusarviointiResourceIT.kt

Feature/uoelsa 873 avoimet asiat arviointipyynnöt

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Seurantajakso.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/SeurantajaksoRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SeurantajaksoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/EtusivuSeurantajaksoDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/SeurantajaksoTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SeurantajaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaEtusivuResource.kt
src/main/resources/config/liquibase/changelog/20220705104249_modify_entity_Seurantajakso.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSeurantakeskustelutResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaEtusivuResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaSeurantakeskustelutResourceIT.kt

UOELSA-874: Seurantajaksot kouluttajan etusivulle

---

detekt-config.yml
src/main/kotlin/fi/elsapalvelu/elsa/domain/Opintoopas.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/ArviointiasteikkoRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/OpintoopasRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ArviointiasteikkoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintoopasService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/OpintoopasDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/OpintoopasSimpleDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/kayttajahallinta/KayttajahallintaErikoistuvaLaakariFormDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ArviointiasteikkoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintoopasServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/OpintoopasMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/OpintoopasSimpleMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaOpetussuunnitelmatResource.kt
src/main/resources/config/liquibase/changelog/20220712141852_modify_entity_Opintoopas.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaOpetussuunnitelmatResourceIT.kt

UOELSA-919: Opinto-oppaiden hallinta tekniselle pääkäyttäjälle

---

src/main/kotlin/fi/elsapalvelu/elsa/service/OpintoopasService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintoopasServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaOpetussuunnitelmatResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaOpetussuunnitelmatResourceIT.kt

UOELSA-919: Kopioi tiedot uusimmasta opinto-oppaasta

---

src/main/graphql/fi.elsapalvelu.elsa/OpintosuorituksetPeppiOulu.graphql
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiOuluOpintosuorituksetFetchingServiceImpl.kt
src/main/resources/config/liquibase/changelog/20220816104134_add_osakokonaisuus_kurssikoodit_oulu.xml
src/main/resources/config/liquibase/master.xml

UOELSA-650: Lisää osasuoritusten käsittely Oulun Peppiä varten

---

src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ErikoistumisenEdistyminenDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt

UOELSA-1142: Lisää tieto koejakson suoritusmerkinnästä

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintosuorituksetPersistenceServiceImpl.kt

UOELSA-1166: Korjaa opintosuoritusten tuonti

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/ArvioitavaKokonaisuus.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/ArvioitavanKokonaisuudenKategoria.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/ArvioitavanKokonaisuudenKategoriaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/SuoritusarviointiRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ArvioitavaKokonaisuusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ArvioitavanKokonaisuudenKategoriaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SuoritusarviointiService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ArvioitavaKokonaisuusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ArvioitavaKokonaisuusWithErikoisalaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ArvioitavanKokonaisuudenKategoriaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ArvioitavanKokonaisuudenKategoriaWithErikoisalaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ArvioitavaKokonaisuusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ArvioitavanKokonaisuudenKategoriaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SuoritusarviointiServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/ArvioitavaKokonaisuusMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/ArvioitavaKokonaisuusWithErikoisalaMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/ArvioitavanKokonaisuudenKategoriaMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/ArvioitavanKokonaisuudenKategoriaSimpleMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/ArvioitavanKokonaisuudenKategoriaWithErikoisalaMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/SeurantajaksoMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritusarviointiResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaOpetussuunnitelmatResource.kt
src/main/resources/config/liquibase/changelog/20220810170542_modify_entity_ArvioitavanKokonaisuudenKategoria.xml
src/main/resources/config/liquibase/changelog/20220816123221_modify_entity_ArvioitavaKokonaisuus.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariEtusivuResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/ArvioitavanKokonaisuudenKategoriaHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaOpetussuunnitelmatResourceIT.kt

UOELSA-918: Arvioitavien kokonaisuuksien hallinta

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Suorite.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/SuoritteenKategoria.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/SuoritemerkintaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/SuoritteenKategoriaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SuoriteService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SuoritemerkintaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SuoritteenKategoriaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoriteWithErikoisalaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoritteenKategoriaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoritteenKategoriaSimpleDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoritteenKategoriaWithErikoisalaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SuoriteServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SuoritemerkintaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SuoritteenKategoriaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/SuoriteWithErikoisalaMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/SuoritteenKategoriaSimpleMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/SuoritteenKategoriaWithErikoisalaMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaOpetussuunnitelmatResource.kt
src/main/resources/config/liquibase/changelog/20220818130154_modify_entity_SuoritteenKategoria.xml
src/main/resources/config/liquibase/changelog/20220818130250_modify_entity_Suorite.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariEtusivuResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritemerkintaResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/SuoritteenKategoriaHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaOpetussuunnitelmatResourceIT.kt

UOELSA-918: Suoritteiden hallinta pääkäyttäjälle

---

src/main/kotlin/fi/elsapalvelu/elsa/config/ApplicationProperties.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/PeppiCommonOpintosuorituksetFetchingService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/PeppiCommonOpintotietodataFetchingService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiCommonOpintosuorituksetFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiCommonOpintotietodataFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiUefClientBuilderImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiUefOpintosuorituksetFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiUefOpintotietodataFetchingServiceImpl.kt
src/main/resources/config/application.yml

UOELSA-806: Hae opinto-oikeustiedot ja suoritukset Itä-Suomen Pepistä

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/OpintoopasRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/UserServiceImpl.kt
src/test/kotlin/fi/elsapalvelu/elsa/service/OpintotietodataPersistenceServiceIT.kt

UOELSA-1174: Korjaa opinto-oppaan hakukysely

---

src/main/kotlin/fi/elsapalvelu/elsa/config/CacheConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/Valmistumispyynto.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KayttajaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/ValmistumispyyntoRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ValmistumispyyntoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/constants/Constants.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ValmistumispyyntoDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ValmistumispyyntoErikoistujaSaveDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ValmistumispyyntoSuoritustenTilaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/VanhentuneetSuorituksetDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/ValmistumispyynnonTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/ValmistumispyyntoMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariValmistumispyyntoResource.kt
src/main/resources/config/liquibase/changelog/20220826120643_added_entity_Valmistumispyynto.xml
src/main/resources/config/liquibase/master.xml
src/main/resources/i18n/messages.properties
src/main/resources/templates/mail/uusivalmistumispyynto.html
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariValmistumispyyntoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/ErikoisalaHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/ErikoistuvaLaakariHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/OpintosuoritusHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/TyoskentelyjaksoHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/TyoskentelypaikkaHelper.kt

Feature/uoelsa 836 erikoistuja lähettää valmistumispyynnön

---

src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoisalaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ErikoisalaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajahallintaResource.kt

UOELSA-1177: Salli vastuuhenkilön lisääminen kaikille erikoisaloille

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Koulutussuunnitelma.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoulutussuunnitelmaDTO.kt
src/main/resources/config/liquibase/changelog/20220907125558_modify_entity_Koulutussuunnitelma.xml
src/main/resources/config/liquibase/master.xml

UOELSA-878: Koulutussuunnitelmaan muokkauspäivä mukaan

---

src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritusarviointiResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritusarviointiResourceIT.kt

UOELSA-880: Palautetaan erikoistujan opinto-oppaan arvioitavien kokonaisuuksien tiedot

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/TerveyskeskuskoulutusjaksonHyvaksynta.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/TerveyskeskuskoulutusjaksonHyvaksyntaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/MailService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/TerveyskeskuskoulutusjaksonHyvaksyntaQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/TerveyskeskuskoulutusjaksonHyvaksyntaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/criteria/TerveyskeskuskoulutusjaksoCriteria.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TerveyskeskuskoulutusjaksoSimpleDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TerveyskeskuskoulutusjaksoUpdateDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TerveyskeskuskoulutusjaksonHyvaksyntaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TyoskentelyjaksotTableDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/TerveyskeskuskoulutusjaksoTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TerveyskeskuskoulutusjaksonHyvaksyntaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/TerveyskeskuskoulutusjaksonHyvaksyntaMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaTerveyskeskuskoulutusjaksoResource.kt
src/main/resources/config/liquibase/changelog/20220908152328_modify_entity_TerveyskeskuskoulutusjaksonHyvaksynta.xml
src/main/resources/config/liquibase/master.xml
src/main/resources/i18n/messages.properties
src/main/resources/templates/mail/tkkjaksonHyvaksymishakemusHyvaksytty.html
src/main/resources/templates/mail/tkkjaksonHyvaksymishakemusPalautettu.html
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/ErikoistuvaLaakariHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaTerveyskeskuskoulutusjaksoResourceIT.kt

UOELSA-834: Terveyskeskuskoulutusjakson tarkastus virkailijalle

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Tyoskentelyjakso.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TyoskentelyjaksoDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KeskeytysaikaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TerveyskeskuskoulutusjaksonHyvaksyntaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/main/resources/config/liquibase/changelog/20220915162419_modify_entity_Tyoskentelyjakso.xml
src/main/resources/config/liquibase/master.xml

UOELSA-835: Lukitaan hyväksyttyyn terveyskoulutusjaksoon liittyvät työskentelyjaksot

---

src/main/kotlin/fi/elsapalvelu/elsa/service/dto/UusiLahikouluttajaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariMuutToiminnotResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariMuutToiminnotResourceIT.kt

UOELSA-1176: Erota lisätyn kouluttajan etu- ja sukunimi

---

src/main/kotlin/fi/elsapalvelu/elsa/config/ApplicationProperties.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/enumeration/OpintooikeudenTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/extensions/OkHttp3Extensions.kt
src/main/kotlin/fi/elsapalvelu/elsa/security/AccessTokenAuthenticator.kt
src/main/kotlin/fi/elsapalvelu/elsa/security/AuthenticationToken.kt
src/main/kotlin/fi/elsapalvelu/elsa/security/AuthenticationTokenCache.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/AuthenticationTokenService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SisuTreAccessTokenProvider.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/constants/Constants.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/AuthenticationTokenClientBuilderImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintotietodataPersistenceServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiCommonOpintosuorituksetFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiCommonOpintotietodataFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuHyOpintotietodataFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuTreAccessTokenClientBuilderImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuTreAccessTokenProviderImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuTreAuthenticationTokenServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuTreClientBuilderImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuTreOpintosuorituksetFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuTreOpintotietodataFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuTutkintoohjelmaFetchingServiceImpl.kt
src/main/resources/config/application.yml
src/test/kotlin/fi/elsapalvelu/elsa/service/OpintotietodataPersistenceServiceIT.kt

UOELSA-649: Hae opinto-oikeustiedot ja suoritukset Tampereen Sisusta

---

src/main/kotlin/fi/elsapalvelu/elsa/service/TyoskentelyjaksoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVastuuhenkilonArvioServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt

UOELSA-1189: Haetaan E-lomakkeelle vain koejaksoon liitetyt työskentelyjaksot

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/AsiakirjaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/AsiakirjaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/AsiakirjaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloTerveyskeskuskoulutusjaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaTerveyskeskuskoulutusjaksoResource.kt

UOELSA-834: Terveyskeskuskoulutusjakson liitteiden lataus virkailijalle ja vastuuhenkilölle

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/AsiakirjaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonVastuuhenkilonArvioRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/AsiakirjaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KoejaksonVastuuhenkilonArvioService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/AsiakirjaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVastuuhenkilonArvioServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloKoejaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaKoejaksoResource.kt

UOELSA-1190: Korjattu koejaksoon liitettyjen työskentelyjaksojen liitteiden lataus virkailijalle ja vastuuhenkilölle

---

src/main/kotlin/fi/elsapalvelu/elsa/security/ElsaSwitchUserFilter.kt

UOELSA-837: Palaa alkuperäiseen osoitteeseen impersonoinnin jälkeen

---

src/main/scripts/HetuDecrypter.kts

- [ei ole] Testit
- [lisätään eduuni wikiin] Dokumentaatio
- [ei ole] Auditointitaulut

Lisää hetun decryptaus skripti

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/ValmistumispyynnonTarkistusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/ValmistumispyyntoRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ValmistumispyyntoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ValmistumispyyntoHyvaksyntaFormDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloValmistumispyyntoResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/ValmistumispyynnonTarkistusHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloValmistumispyyntoResourceIT.kt

UOELSA-1193: Vastuuhenkilo hyvaksyy valmistumispyynnon

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Valmistumispyynto.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SarakesignService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ValmistumispyyntoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ValmistumispyyntoDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/sarakesign/SarakeSignResponseRequestDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKoulutussopimusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SarakesignServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/ValmistumispyyntoMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloValmistumispyyntoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaValmistumispyyntoResource.kt
src/main/resources/config/liquibase/changelog/20221031153118_modify_entity_Valmistumispyynto.xml
src/main/resources/config/liquibase/master.xml

UOELSA-841: Valmistumispyynnon asiakirjojen lataus

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/ArvioitavaKokonaisuusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ArvioitavaKokonaisuusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ArvioitavaKokonaisuusByErikoisalaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ArvioitavaKokonaisuusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/SuoritusarviointiResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaSuoritusarviointiResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloSuoritusarviointiResource.kt

UOELSA-1183: Arvioitavien kokonaisuuksien kuvaukset kouluttajalle ja vastuuhenkilölle

---

src/main/kotlin/fi/elsapalvelu/elsa/service/KoejaksonVastuuhenkilonArvioService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVaiheetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVastuuhenkilonArvioServiceImpl.kt

UOELSA-1211: Koejakson E-lomakkeen allekirjoituksen tilan tarkistus

---

src/main/kotlin/fi/elsapalvelu/elsa/scheduler/ScheduledTerveyskeskuskoulutusjaksoSuoritusmerkinta.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/TerveyskeskuskoulutusjaksonHyvaksyntaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TerveyskeskuskoulutusjaksonHyvaksyntaServiceImpl.kt

UOELSA-1167: Jos terveyskeskuskoulutusjakson hyväksyntä on haettavissa, lisätään linkki avoimiin asioihin

---

src/main/kotlin/fi/elsapalvelu/elsa/service/dto/sarakesign/SarakeSignResponseRequestDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt

UOELSA-1220: Sarake sign palauttaa allekirjoitusajan aikavyöhyketiedon kanssa

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/ArvioitavaKokonaisuusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ArvioitavaKokonaisuusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/criteria/ArvioitavaKokonaisuusCriteria.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ArvioitavaKokonaisuusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/SuoritusarviointiResource.kt

UOELSA-1183: Arvioitavien kokonaisuuksien kuvauksien haku sivutettuna

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/ValmistumispyynnonTarkistus.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ValmistumispyynnonTarkistusUpdateDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/resources/config/liquibase/changelog/20221207144106_modify_entity_ValmistumispyynnonTarkistus.xml
src/main/resources/config/liquibase/master.xml

UOELSA-1202: Valmistumispyynnon koejakson tila opintosuoritteista ja koejaksoa ei vaadittu valinta

---

src/main/kotlin/fi/elsapalvelu/elsa/service/dto/UusiValmistumispyyntoDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ValmistumispyyntoHyvaksyntaFormDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt

UOELSA-1203: Valmistumispyyntöön erikoistujan ja vastuuhenkilön sähköpostin ja puhelinnumeron päivitys

---

src/main/kotlin/fi/elsapalvelu/elsa/service/TyoskentelyjaksoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt

UOELSA-1223: Sallitaan työskentelyjakson kaikkien kenttien muokkaus aina

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/TyoskentelyjaksoRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TerveyskeskuskoulutusjaksonHyvaksyntaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/TyoskentelyjaksoHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloTerveyskeskuskoulutusjaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaTerveyskeskuskoulutusjaksoResourceIT.kt

UOELSA-1225: Terveyskeskuskoulutusjakson käytännönkoulutustyypin huomiointi

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuTreAuthenticationTokenServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariAsiakirjaResource.kt

UOELSA-843: Piilotetaan erikoistujan tietojen asiakirja myös virkailijoilta

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/Opintooikeus.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintooikeusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ErikoistuvaLaakariDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/OpintooikeusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintooikeusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/ErikoistuvaLaakariMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariMuutToiminnotResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTeoriakoulutusResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/main/resources/config/liquibase/changelog/20221212140020_modify_entity_Opintooikeus.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaEtusivuResourceIT.kt

UOELSA-815: Erikoistuja valtuuttaa virkailijan tekemään muutoksia työskentelyjaksoihin ja teoriakoulutuksiin

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/ErikoistuvaLaakariMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariMuutToiminnotResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTeoriakoulutusResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt

UOELSA-815: Virkailijalla oikeus myös lisätä ja poistaa työskentelyjaksoja ja teoriakoulutuksia

---

src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TyoskentelyjaksotTilastotKoulutustyypitDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt

UOELSA-621: Terveyskeskusjakson maksimipituuden huomiointi tilastoissa

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Tyoskentelyjakso.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TyoskentelyjaksoDTO.kt
src/test/kotlin/fi/elsapalvelu/elsa/service/OverlappingTyoskentelyjaksoValidationServiceTest.kt

UOELSA-1223: Palautetaan työskentelyjakson alkamispäivän maksimi

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt

UOELSA-612: Työskentelyjaksoissa täytyy näkyä koko työskentelyaika

---

src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ValmistumispyynnonTarkistusDTO.kt

UOELSA-1202: Koejaksoa ei vaadittu tieto puuttuu tarkistuksen tiedoista

---

src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoistuvaLaakariService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/LaillistamispaivaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ErikoistuvaLaakariServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariMuutToiminnotResource.kt

UOELSA-662: Erikoistujan profiilin laillistamispäivä ja tietojen päivitys

---

src/main/graphql/fi.elsapalvelu.elsa/schema.graphqls

UOELSA-1233: Opintosuoritteelle ei tule aina opintopisteitä pepistä

---

src/main/kotlin/fi/elsapalvelu/elsa/service/KayttajaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KayttajaTiedotDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KayttajaYliopistoErikoisalatDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/OmatTiedotDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajaResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/common/KayttajaResourceIT.kt

UOELSA-973: Kouluttajan ja vastuuhenkilön profiili

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KayttajaTiedotDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajaResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/common/KayttajaResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/KayttajaHelper.kt

UOELSA-664: Virkailijan profiili

---

src/main/kotlin/fi/elsapalvelu/elsa/config/CacheConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/Ilmoitus.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/IlmoitusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/IlmoitusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/IlmoitusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/IlmoitusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/IlmoitusMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/common/JulkisetToiminnotResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaIlmoituksetResource.kt
src/main/resources/config/liquibase/changelog/20230124153427_added_entity_Ilmoitus.xml
src/main/resources/config/liquibase/master.xml

UOELSA-1232: Julkisten ilmoitusten hallinta

---

src/main/kotlin/fi/elsapalvelu/elsa/config/CacheConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/SuoritusarvioinninArvioitavaKokonaisuus.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/Suoritusarviointi.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/SuoritusarvioinninArvioitavaKokonaisuusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/SuoritusarviointiRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SuoritusarviointiQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/criteria/SuoritusarviointiCriteria.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ArvioitavaKokonaisuusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ArvioitavaKokonaisuusWithArvioinnitDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SeurantajaksonArviointiDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SeurantajaksonArviointiKokonaisuusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoritusarvioinninArvioitavaKokonaisuusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoritusarviointiByKokonaisuusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoritusarviointiDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SeurantajaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SuoritusarviointiServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/SuoritusarvioinninArvioitavaKokonaisuusMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/SuoritusarviointiMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/SuoritusarviointiResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritusarviointiResource.kt
src/main/resources/config/liquibase/changelog/20230126154341_modify_entity_Suoritusarviointi.xml
src/main/resources/config/liquibase/master.xml
src/main/resources/templates/pdf/erikoistujantiedot/arviointi.html
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritusarviointiResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/SuoritusarviointiHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaSuoritusarviointiResourceIT.kt

UOELSA-1205: Suoritusarviointi voi sisältää usean arvioitavan kokonaisuuden arvioinnit

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/KoejaksonKoulutussopimus.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KoejaksonKoulutussopimusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/KoejaksoTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKoulutussopimusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVaiheetServiceImpl.kt
src/main/resources/config/liquibase/changelog/20230214124926_modify_entity_KoejaksonKoulutussopimus.xml
src/main/resources/config/liquibase/master.xml
src/main/resources/templates/mail/koulutussopimusHyvaksytty.html
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaKoejaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloKoejaksoResourceIT.kt

UOELSA-1242: Koejakson koulutussopimuksen allekirjoituksen poisto

---

src/main/kotlin/fi/elsapalvelu/elsa/scheduler/ScheduledOpintotietoImport.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintosuorituksetFetchingService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintotietodataFetchingService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintotietodataPersistenceService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintotietodataPersistenceServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiOuluOpintosuorituksetFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiOuluOpintotietodataFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiTurkuOpintosuorituksetFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiTurkuOpintotietodataFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiUefOpintosuorituksetFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiUefOpintotietodataFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuHyOpintosuorituksetFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuHyOpintotietodataFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuTreOpintosuorituksetFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuTreOpintotietodataFetchingServiceImpl.kt

UOELSA-1237: Opintotietojen ja suoritusten päivittäminen päivittäin

---

src/main/kotlin/fi/elsapalvelu/elsa/service/SarakesignService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/sarakesign/SarakeSignRecipientDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVastuuhenkilonArvioServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SarakesignServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt

UOELSA-1191: Tieto virkailijoille ja erikoistujalle sarake sign allekirjoituksesta

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/User.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KayttajaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/UserService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/UserDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ErikoistuvaLaakariServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintotietodataPersistenceServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/UserServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajaResource.kt
src/main/resources/config/liquibase/changelog/20230222115925_modify_entity_User.xml
src/main/resources/config/liquibase/master.xml

UOELSA-1147: Tuki useammalle roolille käyttäjällä

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajaServiceImpl.kt
src/main/resources/i18n/messages.properties
src/main/resources/templates/mail/uusiKouluttajaRooli.html

UOELSA-1276: Heräte erikoistujalle kouluttajan roolin lisäämisestä

---

src/main/kotlin/fi/elsapalvelu/elsa/service/TerveyskeskuskoulutusjaksonHyvaksyntaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ValmistumispyyntoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ValmistumispyynnonTarkistusUpdateDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TerveyskeskuskoulutusjaksonHyvaksyntaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaTerveyskeskuskoulutusjaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaValmistumispyyntoResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaTerveyskeskuskoulutusjaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaValmistumispyyntoResourceIT.kt

UOELSA-1231: Mahdollisuus muokata laillistamispäivää lomakkeilla

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Opintooikeus.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/Opintoopas.kt
src/main/resources/config/liquibase/changelog/20230324122533_added_Opintooikeus_audit.xml
src/main/resources/config/liquibase/master.xml

UOELSA-1278: Opinto-oikeuksien ja oppaiden auditointi

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintooikeusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintotietodataPersistenceServiceImpl.kt

UOELSA-1286: Kouluttaja ei pääse kirjautumaan, jos hänelle löytyy vanhentunut opinto-oikeus

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/KoejaksonVastuuhenkilonArvio.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonVastuuhenkilonArvioRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KoejaksonVastuuhenkilonArvioQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonVastuuhenkilonArvioDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/KoejaksoTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVaiheetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVastuuhenkilonArvioServiceImpl.kt
src/main/resources/config/liquibase/changelog/20230403133331_modify_entity_KoejaksonVastuuhenkilonArvio.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaEtusivuResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaKoejaksoResourceIT.kt

UOELSA-1267: Koejakson arviointilomakkeen palautus vastuuhenkilölle ja palautuksen syy virkailijalle

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt

UOELSA-1272: Valmistumisen palautuksen syy näkyviin virkailijalle

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/TerveyskeskuskoulutusjaksonHyvaksynta.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/TerveyskeskuskoulutusjaksonHyvaksyntaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/TerveyskeskuskoulutusjaksonHyvaksyntaQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TerveyskeskuskoulutusjaksonHyvaksyntaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/TerveyskeskuskoulutusjaksoTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TerveyskeskuskoulutusjaksonHyvaksyntaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/main/resources/config/liquibase/changelog/20230411121531_modify_entity_TerveyskeskuskoulutusjaksonHyvaksynta.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloTerveyskeskuskoulutusjaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaTerveyskeskuskoulutusjaksoResourceIT.kt

UOELSA-1272: Tk-jakson hyväksynnän palautuksen syy näkyviin virkailijalle

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Valmistumispyynto.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt

UOELSA-1274: Valmistumispyynnön osaamisen tarkistetaan vain kerran

---

src/main/kotlin/fi/elsapalvelu/elsa/service/SuoritemerkintaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoritemerkinnanSuoriteDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/UusiSuoritemerkintaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SuoritemerkintaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritemerkintaResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariSuoritemerkintaResourceIT.kt

UOELSA-1217: Useamman suoritteen lisäys kerralla

---

src/main/kotlin/fi/elsapalvelu/elsa/service/OpintooikeusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/kayttajahallinta/KayttajahallintaErikoistuvaLaakariUpdateDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/kayttajahallinta/KayttajahallintaOpintooikeusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintooikeusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajahallintaResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaKayttajahallintaResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaKayttajahallintaResource.kt

UOELSA-1279: Opinto-oikeuden osaamisen arvioinnin oppaan päivämäärän muokkaus

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/TyoskentelyjaksoRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/TyoskentelyjaksoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ValmistumispyynnonTarkistusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt

UOELSA-1288: Valmistumispyynnölle tieto tutkimustyöstä

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariValmistumispyyntoResourceIT.kt

UOELSA-1288: 9kk tkk-jakso katsotaan koulutustyypistä, ei työskentelyjakson tyypistä

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/ValmistumispyynnonTarkistus.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ValmistumispyynnonTarkistusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ValmistumispyynnonTarkistusUpdateDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/resources/config/liquibase/changelog/20230502142015_modify_entity_ValmistumispyynnonTarkistus.xml
src/main/resources/config/liquibase/master.xml

UOELSA-1290: Valmistumisen 9kk tkk-jakson tarkistus

---

src/main/kotlin/fi/elsapalvelu/elsa/service/ValmistumispyyntoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaValmistumispyyntoResource.kt

UOELSA-1291: Valmistumisen liitteiden lataus kaikille saman yliopiston virkailijoille

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt

UOELSA-1298: Korjaus Hakan testiympäristön SAML pyynnön signaturen muodostamiseen

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Opintooikeus.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/enumeration/OpintooikeudenTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/ErikoistuvaLaakariRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/OpintooikeusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/scheduler/ScheduledOpintotietoImport.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoistuvaLaakariService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ErikoistuvaLaakariServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintooikeusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintotietodataPersistenceServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiOuluOpintotietodataFetchingServiceImpl.kt
src/main/resources/config/liquibase/changelog/20230504151405_modify_entity_Opintooikeus.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKaytonAloitusResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/OpintooikeusHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloEtusivuResourceIT.kt

UOELSA-1253: Päättyneiden opinto-oikeuksien katselu

---

src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoistujienSeurantaQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/criteria/ErikoistujanEteneminenCriteria.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaEtusivuResourceIT.kt

UOELSA-1296: Piilotetaan päättyneet opinto-oikeudet erikoistujien seurannasta

---

src/main/kotlin/fi/elsapalvelu/elsa/service/KayttajaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/kayttajahallinta/KayttajahallintaKayttajaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajahallintaResource.kt

UOELSA-1151: Kouluttajan tietojen muokkaus ja kutsun uudelleenlähetys

---

src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoistujienSeurantaQueryService.kt

UOELSa-1296: Ei näytetä opinto-oikeuksia seurannassa viimeisen katselupäivän jälkeen

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksonPituusCounterServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/common/MuutToiminnotResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/service/TyoskentelyjaksonPituusCounterServiceTest.kt
src/test/kotlin/fi/elsapalvelu/elsa/service/helpers/TyoskentelyjaksoMockHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt

UOELSA-1146: Aiemmin hyväksyttyjen työskentelyjaksojen vaikutus laskentaan max 50%

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/OpintosuoritusKurssikoodiRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/OpintosuoritusTyyppiRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintosuoritusKurssikooditService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintosuoritusTyyppiService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/OpintosuoritusKurssikoodiDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintosuoritusKurssikoodiServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintosuoritusTyyppiServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/OpintosuoritusKurssikoodiMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaKurssikooditResource.kt
src/main/resources/config/liquibase/changelog/20220322132551_added_entity_OpintosuoritusTyyppi.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/KurssikoodiHelper.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaKurssikoodiResourceIT.kt

UOELSA-917: Kurssikoodien ylläpito virkailijalle

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonAloituskeskusteluRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonKehittamistoimenpiteetRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonKoulutussopimusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonLoppukeskusteluRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonValiarviointiRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KouluttajavaltuutusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/SeurantajaksoRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/SuoritusarviointiRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KayttajaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/UserService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/criteria/KayttajahallintaCriteria.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/kayttajahallinta/KayttajahallintaKayttajaWrapperDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/kayttajahallinta/KayttajahallintaReassignedKouluttajaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/UserServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajahallintaResource.kt

UOELSA-1301: Kutsutun kouluttajan poisto

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/KayttajaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KayttajaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/common/MuutToiminnotResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariMuutToiminnotResource.kt

UOELSA-1303: Listataan kaikki saman erikoisalan kouluttajat yliopistosta riippumatta

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonAloituskeskusteluRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonKehittamistoimenpiteetRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonLoppukeskusteluRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonValiarviointiRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVaiheetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KoejaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/SeurantakeskustelutResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/common/MuutToiminnotResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaKoejaksoCommonResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaKoejaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloKoejaksoCommonResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloKoejaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloSeurantakeskustelutResource.kt

UOELSA-1295: Seurantakeskustelut ja koejakson vaiheet vastuuhenkilölle

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/KayttajaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonAloituskeskusteluRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonKehittamistoimenpiteetRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonKoulutussopimusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonLoppukeskusteluRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonValiarviointiRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/SeurantajaksoRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/SuoritusarviointiRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KayttajaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/UserService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/criteria/KayttajahallintaCriteria.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/kayttajahallinta/KayttajahallintaKayttajaWrapperDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/UserServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajahallintaResource.kt

UOELSA-1152: Kouluttajan passivointi

---

src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajahallintaResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/errors/BadRequestExceptionAdvice.kt

UOELSA-1153: Vastuuhenkilöä ei voi passivoida, jos siihen liittyy vastuualueita

---

src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ArvioitavaKokonaisuusWithErikoisalaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/SuoriteWithErikoisalaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ArvioitavaKokonaisuusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SuoriteServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/TekninenPaakayttajaOpetussuunnitelmatResource.kt

UOELSA-1182: Suoritteiden ja arvioitavien kokonaisuuksien poisto

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/KoejaksonKoulutussopimus.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonAloituskeskusteluRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonKehittamistoimenpiteetRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonKoulutussopimusRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonLoppukeskusteluRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonValiarviointiRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/repository/KoejaksonVastuuhenkilonArvioRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonKoulutussopimusDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/KoejaksoTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonAloituskeskusteluServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKehittamistoimenpiteetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKoulutussopimusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonLoppukeskusteluServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVaiheetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonValiarviointiServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVastuuhenkilonArvioServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaKoejaksoResource.kt
src/main/resources/config/liquibase/changelog/20230619130654_modify_entity_KoejaksonKoulutussopimus.xml
src/main/resources/config/liquibase/changelog/20230620121212_modify_entity_KoejaksonVastuuhenkilonArvio.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloEtusivuResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloKoejaksoResourceIT.kt

UOELSA-1179: Vastuuhenkilön viittauksen muutokset koejaksoissa

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Opintooikeus.kt

UOELSA-1313: Kaikkien opinto-oikeuksien haussa loppuu muisti

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PdfServiceImpl.kt

UOELSA-1314: Korruptoituneet tiedostot eivät saa kaataa pdf:n generointia

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/ErikoistuvaLaakari.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ErikoistuvaLaakariServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TerveyskeskuskoulutusjaksonHyvaksyntaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/TerveyskeskuskoulutusjaksonHyvaksyntaMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/ValmistumispyyntoMapper.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/mapper/ValmistumispyyntoOsaamisenArviointiMapper.kt
src/main/resources/config/liquibase/changelog/20230705141626_modify_entity_ErikoistuvaLaakari.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariValmistumispyyntoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/ErikoistuvaLaakariHelper.kt

UOELSA-1313: Laillistamistodistuksen datan siirtäminen omaan tauluun muistin käytön optimoimiseksi

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Asiakirja.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/KoejaksonVastuuhenkilonArvio.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/AsiakirjaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KoejaksonVastuuhenkilonArvioService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonVastuuhenkilonArvioDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/AsiakirjaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVastuuhenkilonArvioServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloKoejaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaKoejaksoResource.kt
src/main/resources/config/liquibase/changelog/20230706093836_modify_entity_Asiakirja.xml
src/main/resources/config/liquibase/master.xml
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResourceIT.kt

UOELSA-1307: Koejakson vastuuhenkilön arvioon liitteet

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/KoejaksonVastuuhenkilonArvio.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoejaksonVastuuhenkilonArvioDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVaiheetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVastuuhenkilonArvioServiceImpl.kt
src/main/resources/config/liquibase/changelog/20230707111300_modify_entity_KoejaksonVastuuhenkilonArvio.xml
src/main/resources/config/liquibase/master.xml

Kehitystiketti: https://jira.eduuni.fi/browse/UOELSA-1316

UOELSA-1316: Allekirjoituspäivämäärä koe jaksojen listaukseen

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonAloituskeskusteluServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKehittamistoimenpiteetServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonLoppukeskusteluServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonValiarviointiServiceImpl.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloKoejaksoResourceIT.kt

UOELSA-1317: Vastuuhenkilö voi toimia koejakson vaiheissa kouluttajana

---

src/main/kotlin/fi/elsapalvelu/elsa/config/RelyingPartyConfiguration.kt

Hakan kirjautumispyynnöstä puuttuu varmenne

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TerveyskeskuskoulutusjaksonHyvaksyntaServiceImpl.kt

elsa-436-tk-jakson-tyokertyma-raja

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TerveyskeskuskoulutusjaksonHyvaksyntaServiceImpl.kt

Elsa 436 tk jakson tyokertyman raja

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonKoulutussopimusServiceImpl.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKoejaksoResourceIT.kt

elsa-443-koulutussopimukseen-vastuuhenkilon-nimi

---

src/main/resources/config/application.yml

elsa-498-palaute-email-muutos

---

src/main/resources/config/liquibase/changelog/20240319000000_modify_entity_Erikoisala.xml
src/main/resources/config/liquibase/master.xml

ELSA-495: Erikoisala aktiiviseksi migraatio

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoejaksonVastuuhenkilonArvioServiceImpl.kt
src/main/resources/i18n/messages.properties
src/main/resources/templates/mail/virkailijaKoejaksoTarkastettavissa.html

ELSA-439 / Lomake E herate virkailijalle

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/security/ElsaSwitchUserFilter.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajaResource.kt

YEK-1532: YEK-kouluttajan impersonoinnin roolin asetus ja käyttöoikeudet

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/UserDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/yekkoulutettava/YekKoulutettavaEtusivuResource.kt

YEK-1532: YEK-koulutettavan tietojen haku jos ei muita rooleja

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintotietodataPersistenceServiceImpl.kt

YEK-1536: Ei huomioida YEK-opinto-oikeutta opinto-oikeuksien määrän tarkistuksessa

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/Opintoopas.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/OpintoopasDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintoopasServiceImpl.kt
src/main/resources/config/liquibase/changelog/20240516162500_modify_entity_Opintoopas.xml
src/main/resources/config/liquibase/master.xml

YEK-1568: YEK opinto-opas

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/resources/i18n/messages.properties
src/main/resources/templates/mail/valmistumispyyntoHyvaksytty.html
src/main/resources/templates/mail/valmistumispyyntoHyvaksyttyVirkailija.html
src/main/resources/templates/mail/valmistumispyyntoPalautettuMuutYek.html
src/main/resources/templates/mail/valmistumispyyntoTarkastettavissaYek.html

YEK-1570: YEK valmistumispyynnön herätteiden korjaus

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/TyoskentelyjaksoRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/scheduler/ScheduledTerveyskeskuskoulutusjaksoSuoritusmerkinta.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/EtusivuService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintosuoritusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/TerveyskeskuskoulutusjaksonHyvaksyntaService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/enumeration/TerveyskeskuskoulutusjaksoTila.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintosuoritusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TerveyskeskuskoulutusjaksonHyvaksyntaServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/yekkoulutettava/YekKoulutettavaEtusivuResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/yekkoulutettava/YekKoulutettavaTyoskentelyjaksoResource.kt

YEK-1572: 9kk tk-jaksoon opintosuoritteiden huomioiminen ja tuki yekille

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TerveyskeskuskoulutusjaksonHyvaksyntaServiceImpl.kt

YEK-1574: Vaaditaan tk-jakson rooli kaikkiin tk-jaksoihin liittyviin toimintoihin

---

gradle.properties
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintosuoritusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt

Huom! Päivitetty gitPropertiesPluginVersion koska azure devops yritti etsiä grgit-core versiota mitä ei löytynyt enää maven centralista.

YEK-1576: Suodata EL ja YEK puolen opintosuoritukset tyypin mukaan

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt

YEK-1578: Korjauksia YEK työskentelyjaksojen tilastojen laskemiseen

---

src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoistujienSeurantaQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/EtusivuService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/KoulutettavanEteneminenDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloEtusivuResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaEtusivuResource.kt

YEK-1579: Koulutettavien seuranta vastuuhenkilöille ja virkailijoille

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/resources/i18n/messages.properties
src/main/resources/templates/mail/valmistumispyyntoTarkastettavissaYek.html

YEK-1581: YEK valmistumispyynnön tekstikorjauksia

---

azure-pipelines.yml

CI ajaa tarvittavat tarkistukset, PR trigger ajaa saman pipelinen turhaan uudestaan.

PR triggerien poisto käytöstä

---

src/main/kotlin/fi/elsapalvelu/elsa/service/dto/TyoskentelyjaksotTilastotKoulutustyypitDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TyoskentelyjaksoServiceImpl.kt

YEK-1587: Korjaus muun työskentelyn maksimin huomioimiseen

---

src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajahallintaResource.kt

YEK-1590: YEK pois vastuuhenkilön tehtävien erikoisalalistauksesta

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintotietodataPersistenceServiceImpl.kt
src/test/kotlin/fi/elsapalvelu/elsa/service/OpintotietodataPersistenceServiceIT.kt

YEK-1583: Asetetaan erikoistujan rooli opinto-oikeuden perusteella

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiOuluOpintotietodataFetchingServiceImpl.kt

yek-1594-oulu-asetuksen-muokkaus

---

.github/workflows/actions.yml

- Muutettu nimeämisiä
- Korjattu huoltokatkosivun näyttäminen
- Ajetaan prod deploy aina vasta stagingin jälkeen

Github Actions korjauksia

---

.github/workflows/actions.yml

Github actions ECS service nimen korjaus

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajienYhdistaminenServiceImpl.kt

ELSA-397: käyttäjät asetettiin väärin

---

src/main/kotlin/fi/elsapalvelu/elsa/domain/ErikoistuvaLaakari.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoistuvaLaakariService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/ErikoistujanEteneminenDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/LaillistamispaivaDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ErikoistuvaLaakariServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariMuutToiminnotResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/yekkoulutettava/YekKoulutettavaMuutToiminnotResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/yekkoulutettava/YekKoulutettavaTyoskentelyjaksoResource.kt
src/main/resources/config/liquibase/changelog/20241007134300_modify_entity_ErikoistuvaLaakari.xml
src/main/resources/config/liquibase/master.xml

YEK-1595: Lääkarikoulutus suoritettu muutokset

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/KayttajaYliopistoErikoisalaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajienYhdistaminenServiceImpl.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/KayttajahallintaResourceIT.kt

ELSA-397: Lisää korjauksia

---

gradle.properties

Jib plugin version päivitys

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/SeurantajaksoRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajienYhdistaminenServiceImpl.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/tekninenpaakayttaja/KayttajahallintaResourceIT.kt

Lisätään mahdollisuus valita yek koulutettava erikoistuvan lisäksi. 
Lisätään yhdistettäviin seurantajakson kouluttaja

Elsa 397 lisataan yek koulutettava tilien yhdistamiseen

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt

ELSA-718 yek valmistumispyynnön heräte korjaus

---

src/main/kotlin/fi/elsapalvelu/elsa/service/ValmistumispyyntoService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ValmistumispyyntoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariValmistumispyyntoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/vastuuhenkilo/VastuuhenkiloValmistumispyyntoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaValmistumispyyntoResource.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaValmistumispyyntoResourceIT.kt

ELSA-710: Valmistumispyynnon tilojen validointi

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt

ELSA-716: Ei tk-jaksoa avoimiin asioihin jos suoritus löytyy

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt

ELSA-731: YEK koulutettavalle oikeudet päivittää profiilia

---

.github/workflows/dependencies.yml
build.gradle

Ei päivitetä NVD cachea joka ajolla, koska API ei ole stabiili

---

src/main/kotlin/fi/elsapalvelu/elsa/config/CacheConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/User.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/VerificationToken.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoistujienSeurantaQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/KoejaksonVastuuhenkilonArvioQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/PaivakirjamerkintaQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/SuoritusarviointiQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/TerveyskeskuskoulutusjaksonHyvaksyntaQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ErikoistuvaLaakariQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/EtusivuServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KayttajaQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/KayttajahallintaResource.kt

- Specification apin refaktorointi siistimmäksi
- SecurityConfiguration muutokset uusimman spring päivityksen jälkeen
- Uusi UUID generator syntaksi

Build varoituksien korjauksia

---

build.gradle
gradle.properties
src/main/kotlin/fi/elsapalvelu/elsa/config/RelyingPartyConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/KoulutusjaksoServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/LogoutResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/RedirectResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResource.kt
src/main/kotlin/fi/elsapalvelu/elsa/web/rest/yekkoulutettava/YekKoulutettavaTyoskentelyjaksoResource.kt
src/main/resources/config/application.yml
src/test/kotlin/fi/elsapalvelu/elsa/config/timezone/HibernateTimeZoneIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/service/OpintotietodataPersistenceServiceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/common/KayttajaResourceWithMockUserIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariEtusivuResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariKaytonAloitusResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariTyoskentelyjaksoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/erikoistuvalaakari/ErikoistuvaLaakariValmistumispyyntoResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/kouluttaja/KouluttajaEtusivuResourceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/virkailija/VirkailijaEtusivuResourceIT.kt
src/test/resources/config/application.yml

- Spring Boot 3.4.1 
- Spring Security 6.4.2
- Hibernate 6.6.4: https://docs.jboss.org/hibernate/orm/6.2/migration-guide/migration-guide.html#enhancement 
- Kotlin 2.0.10
- Paremmat virhelokit kirjautumisen virheistä

Kirjastojen päivityksiä ja kirjautumisen virhelokin parannus

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiOuluOpintosuorituksetFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PeppiOuluOpintotietodataFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuHyOpintosuorituksetFetchingServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/SisuHyOpintotietodataFetchingServiceImpl.kt

Apollo virheisiin stacktrace mukaan

---

src/main/resources/config/application.yml

ELSA-827: Suomi.fi autentikaation POST-kutsusta häviää sessio

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/ErikoistujienSeurantaQueryService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/OpintooikeusService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintooikeusServiceImpl.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintotietodataPersistenceServiceImpl.kt
src/test/kotlin/fi/elsapalvelu/elsa/service/OpintooikeusServiceIT.kt
src/test/kotlin/fi/elsapalvelu/elsa/web/rest/helpers/ErikoistuvaLaakariHelper.kt

- kouluttajan, vastuuhenkilön ja virkailijan erikoistujien seurannan korjaus
- erikoistujan roolien päivitys jos oikeus on vanhentunut
- voimassaolevan opinto-oikeuden hakemisen korjauksia

ELSA-746: Opinto-oikeuden paattymisen huomiointi ja roolien päivitys

---

src/main/kotlin/fi/elsapalvelu/elsa/repository/KayttajaRepository.kt
src/main/kotlin/fi/elsapalvelu/elsa/security/ElsaSwitchUserFilter.kt

ELSA-840: Korjaus erikoistujan tietojen katseluun

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt
src/main/kotlin/fi/elsapalvelu/elsa/domain/User.kt

Tyhjän aktiivisen roolin huomiointi

---

src/main/kotlin/fi/elsapalvelu/elsa/config/JacksonConfiguration.kt

PageImpl -> PagedModel konversio

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/OpintotietodataPersistenceServiceImpl.kt

ELSA-853: Päätellään opinto-oikeuden viimeinen katselupäivä oikeuden päättymispäivän mukaan tilan sijaan

---

src/main/kotlin/fi/elsapalvelu/elsa/web/rest/RedirectResource.kt

Ei lokiteta kirjautumisen virheitä joissa payload on tyhjä tai lähde tuntematon. Aiheuttaa tuotannon lokeissa virhettä:
`Unknown authentication exception: Saml2AuthenticationException{error=[relying_party_registration_not_found] No relying party registration found}`
Lisätään samalla kirjautumisen virheisiin lähde IP

ELSA-849: Lokitetaan vain suomi.fi ja haka virheet

---

src/main/resources/config/application.yml

Vaihdetaan palaute osoite

---

src/main/kotlin/fi/elsapalvelu/elsa/config/SecurityConfiguration.kt

- pitäisi toimia suomi.fi ja HAKA kirjautumisten kanssa (SAML)

ELSA-911: Tarkistetaan käyttäjän nimi kirjautumisen yhteydessä

---

.github/workflows/actions.yml
.github/workflows/dependencies.yml

Päivitetään setup gradle action 3 -> 4, jotta cache toimii taas

Gradle cache korjaus

---

src/main/kotlin/fi/elsapalvelu/elsa/service/MailService.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/dto/PalauteDTO.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/PalauteServiceImpl.kt
src/main/resources/templates/mail/palaute.html

Palautelomakkeelta lähtevä sähköposti.
Otsikossa näkyy palautteen lähettäjä, aihe ja yliopisto
Viestiin lisätty yliopisto ja selkeyttämiseksi rivinvaihtoja

Palaute mailin otsikko muutos

---

build.gradle
src/main/kotlin/fi/elsapalvelu/elsa/ElsaBackendApp.kt
src/main/kotlin/fi/elsapalvelu/elsa/service/impl/TampereLouhiService.kt

Korjaus ed25519 algoritmin tukemiseen

---

src/main/kotlin/fi/elsapalvelu/elsa/service/impl/ArkistointiServiceImpl.kt

Korjaus arkistoinnin zip tiedoston tallennukseen ja lähetykseen
